---
name: Build Custom Image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  IMAGE_DESC: "My Customized Universal Blue Image"
  IMAGE_REGISTRY: "code.tjo.space/${{ github.repository_owner }}"
  ARTIFACTHUB_LOGO_URL: "https://code.tjo.space/user/settings#avatar-settings"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_push:
    runs-on: ubuntu-latest
    name: Build and push image
    strategy:
      fail-fast: false
      matrix:
        flavor: [bazzite-deck-gnome, bazzite-gnome]
        version: [42, 43]

    env:
      IMAGE_NAME: "${{ github.event.repository.name }}-${{ matrix.flavor }}"

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@961cad8246f221a1c5f0ecf481fbbf58ee9a1ceb # v0.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.NIX_GITHUB_TOKEN }}
        with:
          enable-cache: false
          github-token: "${{ secrets.NIX_GITHUB_TOKEN }}"

      - name: Get current date
        id: date
        run: |
          # This generates a timestamp like what is defined on the ArtifactHub documentation
          # E.G: 2022-02-08T15:38:15Z'
          # https://artifacthub.io/docs/topics/repositories/container-images/
          # https://linux.die.net/man/1/date
          echo "date=$(date -u +%Y\-%m\-%d\T%H\:%M\:%S\Z)" >> $GITHUB_OUTPUT

      # Image metadata for https://artifacthub.io/ - This is optional but is highly recommended so we all can get a index of all the custom images
      # The metadata by itself is not going to do anything, you choose if you want your image to be on ArtifactHub or not.
      - name: Image Metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        id: metadata
        with:
          # This generates all the tags for your image, you can add custom tags here too!
          # By default, it should generate "latest" and "latest.(date here)".
          tags: |
            type=raw,value=latest
            type=raw,value=latest.{{date 'YYYYMMDD'}}
            type=raw,value={{date 'YYYYMMDD'}}
            type=sha,enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=pr
          labels: |
            io.artifacthub.package.readme-url=https://code.tjo.space/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/raw/refs/heads/main/README.md
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.documentation=https://code.tjo.space/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/raw/refs/heads/main/README.md
            org.opencontainers.image.source=https://code.tjo.space/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/src/branch/main/Containerfile
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=https://code.tjo.space/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=latest
            io.artifacthub.package.deprecated=false
            io.artifacthub.package.keywords=bootc,ublue,universal-blue
            io.artifacthub.package.license=Apache-2.0
            io.artifacthub.package.logo-url=${{ env.ARTIFACTHUB_LOGO_URL }}
            io.artifacthub.package.prerelease=false
            containers.bootc=1
          sep-tags: " "
          sep-annotations: " "

      - name: Build Image
        run: |
          export BUILDAH_ISOLATION=chroot
          devbox run -- buildah build \
            --build-arg=FLAVOR=${{ matrix.flavor }} \
            --build-arg=VERSION=${{ matrix.version }} \
            --file Containerfile \
            --tag ${{ env.IMAGE_NAME }} \
            --label ${{ steps.metadata.outputs.labels }}

      - name: Push image
        id: push
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          echo "${{ secrets.PACKAGES_TOKEN }}" | devbox run -- buildah login -u ${{ github.actor }} --password-stdin
          echo "${{ secrets.PACKAGES_TOKEN }}" | devbox run -- skopeo login -u ${{ github.actor }} --password-stdin

          IMAGE="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          VERSION="${{ steps.metadata.outputs.version }}"

          echo "- Pushing tag ${IMAGE}:${VERSION}"
          devbox run -- buildah push ${{ env.IMAGE_NAME}} docker://${IMAGE}:${VERSION}

          for tag in ${{ steps.metadata.outputs.tags }}; do
            echo "- Copying from ${VERSION} to ${tag}"
            devbox run -- skopeo copy docker://${IMAGE}:${VERSION} docker://${IMAGE}:${tag}
          done

      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          IMAGE_FULL="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"

          for tag in ${{ steps.metadata.outputs.tags }}; do
            devbox run -- cosign sign -y --key env://COSIGN_PRIVATE_KEY $IMAGE_FULL:$tag
          done
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
