---
name: Build Custom Image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    runs-on: nix-latest
    name: Build and push image
    strategy:
      fail-fast: false
      matrix:
        flavor: [bazzite-gnome]
        version: [stable-43, stable-44]

    env:
      IMAGE_NAME: "${{ matrix.flavor }}"
      IMAGE_REGISTRY: "code.tjo.space/mentos1386/os"

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - run: /prepare.sh

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Build Image
        run: |
          IMAGE="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"

          nix develop --command podman build \
            --build-arg FLAVOR=${{ matrix.flavor }} \
            --build-arg VERSION=${{ matrix.version }} \
            --label "org.opencontainers.image.created=$(date -u +%Y\-%m\-%d\T%H\:%M\:%S\Z)" \
            --label "org.opencontainers.image.version=${{ matrix.version }}-${{ github.ref_name }}" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "org.opencontainers.image.title=${{ env.IMAGE_NAME }}" \
            --tag "${IMAGE}" \
            --file Containerfile \
            .

      - name: Push image
        if: forgejo.event_name != 'pull_request' && forgejo.ref_name == 'main'
        run: |
          echo "${{ secrets.PACKAGES_TOKEN }}" | nix develop --command podman login -u mentos1386 --password-stdin code.tjo.space
          echo "${{ secrets.PACKAGES_TOKEN }}" | nix develop --command cosign login -u mentos1386 --password-stdin code.tjo.space

          IMAGE="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"

          for tag in latest ${{ matrix.version }} $(date -u +%Y\%m\%d) ${{ forgejo.ref_name }} ${{ forgejo.sha }}; do
            echo "- Pusing ${tag}"
            nix develop --command podman push ${IMAGE}:latest ${IMAGE}:${tag}
            echo "- Signing ${tag}"
            nix develop --command cosign sign -y --key env://COSIGN_PRIVATE_KEY ${IMAGE}:${tag}
          done
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
